// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/smartpick/emh/v1/metrics.proto

package emh

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------------------
// Comparison definitions
// ----------------------------------------
type DeltaComparisonType int32

const (
	// Default
	DeltaComparisonType_DELTA_COMPARISON_TYPE_UNSPECIFIED DeltaComparisonType = 0
	// Compare to the previous range
	// Ex 1
	// Current: [10/01/2025 00:00:00, 10/01/2025 10:30:00]
	// Previous: [09/30/2025 00:00:00, 09/30/20205 10:30:00]
	// Ex 2
	// Current: [10/01/2025 00:00:00, 10/02/2025 10:30:00]
	// Previous: [09/29/2025 00:00:00, 09/30/20205 10:30:00]
	DeltaComparisonType_DELTA_COMPARISON_TYPE_PREVIOUS DeltaComparisonType = 1
	// Compare to the previou 7 day average
	DeltaComparisonType_DELTA_COMPARISON_TYPE_SEVEN_DAY_AVG DeltaComparisonType = 2
)

// Enum value maps for DeltaComparisonType.
var (
	DeltaComparisonType_name = map[int32]string{
		0: "DELTA_COMPARISON_TYPE_UNSPECIFIED",
		1: "DELTA_COMPARISON_TYPE_PREVIOUS",
		2: "DELTA_COMPARISON_TYPE_SEVEN_DAY_AVG",
	}
	DeltaComparisonType_value = map[string]int32{
		"DELTA_COMPARISON_TYPE_UNSPECIFIED":   0,
		"DELTA_COMPARISON_TYPE_PREVIOUS":      1,
		"DELTA_COMPARISON_TYPE_SEVEN_DAY_AVG": 2,
	}
)

func (x DeltaComparisonType) Enum() *DeltaComparisonType {
	p := new(DeltaComparisonType)
	*p = x
	return p
}

func (x DeltaComparisonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeltaComparisonType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_smartpick_emh_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (DeltaComparisonType) Type() protoreflect.EnumType {
	return &file_proto_smartpick_emh_v1_metrics_proto_enumTypes[0]
}

func (x DeltaComparisonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeltaComparisonType.Descriptor instead.
func (DeltaComparisonType) EnumDescriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{0}
}

// ----------------------------------------
// KPI definitions (scalar values)
// ----------------------------------------
type KpiType int32

const (
	KpiType_KPI_TYPE_UNSPECIFIED           KpiType = 0
	KpiType_KPI_TYPE_TOTAL_TASKS_COMPLETED KpiType = 1
	KpiType_KPI_TYPE_TOTAL_TASKS_MERGED    KpiType = 2
	KpiType_KPI_TYPE_TOTAL_TASKS_CANCELED  KpiType = 3
	KpiType_KPI_TYPE_COMPLETED_RATIO       KpiType = 4
	KpiType_KPI_TYPE_NUM_DRIVERS           KpiType = 5
	KpiType_KPI_TYPE_NUM_FORKLIFTS         KpiType = 6
	KpiType_KPI_TYPE_TOTAL_TASKS           KpiType = 7
	KpiType_KPI_TYPE_TASK_UTILIZATION      KpiType = 8
	KpiType_KPI_TYPE_REALISTIC_TASK_TIME   KpiType = 9
	KpiType_KPI_TYPE_APP_LOGIN             KpiType = 10
	KpiType_KPI_TYPE_APP_TIME              KpiType = 11
)

// Enum value maps for KpiType.
var (
	KpiType_name = map[int32]string{
		0:  "KPI_TYPE_UNSPECIFIED",
		1:  "KPI_TYPE_TOTAL_TASKS_COMPLETED",
		2:  "KPI_TYPE_TOTAL_TASKS_MERGED",
		3:  "KPI_TYPE_TOTAL_TASKS_CANCELED",
		4:  "KPI_TYPE_COMPLETED_RATIO",
		5:  "KPI_TYPE_NUM_DRIVERS",
		6:  "KPI_TYPE_NUM_FORKLIFTS",
		7:  "KPI_TYPE_TOTAL_TASKS",
		8:  "KPI_TYPE_TASK_UTILIZATION",
		9:  "KPI_TYPE_REALISTIC_TASK_TIME",
		10: "KPI_TYPE_APP_LOGIN",
		11: "KPI_TYPE_APP_TIME",
	}
	KpiType_value = map[string]int32{
		"KPI_TYPE_UNSPECIFIED":           0,
		"KPI_TYPE_TOTAL_TASKS_COMPLETED": 1,
		"KPI_TYPE_TOTAL_TASKS_MERGED":    2,
		"KPI_TYPE_TOTAL_TASKS_CANCELED":  3,
		"KPI_TYPE_COMPLETED_RATIO":       4,
		"KPI_TYPE_NUM_DRIVERS":           5,
		"KPI_TYPE_NUM_FORKLIFTS":         6,
		"KPI_TYPE_TOTAL_TASKS":           7,
		"KPI_TYPE_TASK_UTILIZATION":      8,
		"KPI_TYPE_REALISTIC_TASK_TIME":   9,
		"KPI_TYPE_APP_LOGIN":             10,
		"KPI_TYPE_APP_TIME":              11,
	}
)

func (x KpiType) Enum() *KpiType {
	p := new(KpiType)
	*p = x
	return p
}

func (x KpiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KpiType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_smartpick_emh_v1_metrics_proto_enumTypes[1].Descriptor()
}

func (KpiType) Type() protoreflect.EnumType {
	return &file_proto_smartpick_emh_v1_metrics_proto_enumTypes[1]
}

func (x KpiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KpiType.Descriptor instead.
func (KpiType) EnumDescriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{1}
}

// ----------------------------------------
// Table definitions (breakdowns)
// ----------------------------------------
type TableType int32

const (
	TableType_TABLE_TYPE_UNSPECIFIED         TableType = 0
	TableType_TABLE_TYPE_TASKS_BY_DRIVER     TableType = 1
	TableType_TABLE_TYPE_TASKS_BY_DEPARTMENT TableType = 2
	TableType_TABLE_TYPE_TASKS_BY_FORKLIFT   TableType = 3
)

// Enum value maps for TableType.
var (
	TableType_name = map[int32]string{
		0: "TABLE_TYPE_UNSPECIFIED",
		1: "TABLE_TYPE_TASKS_BY_DRIVER",
		2: "TABLE_TYPE_TASKS_BY_DEPARTMENT",
		3: "TABLE_TYPE_TASKS_BY_FORKLIFT",
	}
	TableType_value = map[string]int32{
		"TABLE_TYPE_UNSPECIFIED":         0,
		"TABLE_TYPE_TASKS_BY_DRIVER":     1,
		"TABLE_TYPE_TASKS_BY_DEPARTMENT": 2,
		"TABLE_TYPE_TASKS_BY_FORKLIFT":   3,
	}
)

func (x TableType) Enum() *TableType {
	p := new(TableType)
	*p = x
	return p
}

func (x TableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_smartpick_emh_v1_metrics_proto_enumTypes[2].Descriptor()
}

func (TableType) Type() protoreflect.EnumType {
	return &file_proto_smartpick_emh_v1_metrics_proto_enumTypes[2]
}

func (x TableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableType.Descriptor instead.
func (TableType) EnumDescriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{2}
}

// ----------------------------------------
// Timeseries definitions
// ----------------------------------------
type TimeseriesType int32

const (
	TimeseriesType_TIMESERIES_TYPE_UNSPECIFIED         TimeseriesType = 0
	TimeseriesType_TIMESERIES_TYPE_UTILIZATION         TimeseriesType = 1
	TimeseriesType_TIMESERIES_TYPE_TASK_STATUS         TimeseriesType = 2
	TimeseriesType_TIMESERIES_TYPE_REALISTIC_TASK_TIME TimeseriesType = 3
	TimeseriesType_TIMESERIES_TYPE_APP_LOGIN           TimeseriesType = 4
	TimeseriesType_TIMESERIES_TYPE_APP_TIME            TimeseriesType = 5
)

// Enum value maps for TimeseriesType.
var (
	TimeseriesType_name = map[int32]string{
		0: "TIMESERIES_TYPE_UNSPECIFIED",
		1: "TIMESERIES_TYPE_UTILIZATION",
		2: "TIMESERIES_TYPE_TASK_STATUS",
		3: "TIMESERIES_TYPE_REALISTIC_TASK_TIME",
		4: "TIMESERIES_TYPE_APP_LOGIN",
		5: "TIMESERIES_TYPE_APP_TIME",
	}
	TimeseriesType_value = map[string]int32{
		"TIMESERIES_TYPE_UNSPECIFIED":         0,
		"TIMESERIES_TYPE_UTILIZATION":         1,
		"TIMESERIES_TYPE_TASK_STATUS":         2,
		"TIMESERIES_TYPE_REALISTIC_TASK_TIME": 3,
		"TIMESERIES_TYPE_APP_LOGIN":           4,
		"TIMESERIES_TYPE_APP_TIME":            5,
	}
)

func (x TimeseriesType) Enum() *TimeseriesType {
	p := new(TimeseriesType)
	*p = x
	return p
}

func (x TimeseriesType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeseriesType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_smartpick_emh_v1_metrics_proto_enumTypes[3].Descriptor()
}

func (TimeseriesType) Type() protoreflect.EnumType {
	return &file_proto_smartpick_emh_v1_metrics_proto_enumTypes[3]
}

func (x TimeseriesType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeseriesType.Descriptor instead.
func (TimeseriesType) EnumDescriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{3}
}

type Aggregation int32

const (
	Aggregation_AGGREGATION_UNSPECIFIED Aggregation = 0
	Aggregation_AGGREGATION_AVG         Aggregation = 1
	Aggregation_AGGREGATION_SUM         Aggregation = 2
	Aggregation_AGGREGATION_P50         Aggregation = 3
	Aggregation_AGGREGATION_P90         Aggregation = 4
	Aggregation_AGGREGATION_P99         Aggregation = 5
)

// Enum value maps for Aggregation.
var (
	Aggregation_name = map[int32]string{
		0: "AGGREGATION_UNSPECIFIED",
		1: "AGGREGATION_AVG",
		2: "AGGREGATION_SUM",
		3: "AGGREGATION_P50",
		4: "AGGREGATION_P90",
		5: "AGGREGATION_P99",
	}
	Aggregation_value = map[string]int32{
		"AGGREGATION_UNSPECIFIED": 0,
		"AGGREGATION_AVG":         1,
		"AGGREGATION_SUM":         2,
		"AGGREGATION_P50":         3,
		"AGGREGATION_P90":         4,
		"AGGREGATION_P99":         5,
	}
)

func (x Aggregation) Enum() *Aggregation {
	p := new(Aggregation)
	*p = x
	return p
}

func (x Aggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_smartpick_emh_v1_metrics_proto_enumTypes[4].Descriptor()
}

func (Aggregation) Type() protoreflect.EnumType {
	return &file_proto_smartpick_emh_v1_metrics_proto_enumTypes[4]
}

func (x Aggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggregation.Descriptor instead.
func (Aggregation) EnumDescriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{4}
}

type KpiValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          KpiType                `protobuf:"varint,1,opt,name=type,proto3,enum=proto.smartpick.emh.v1.KpiType" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Delta         float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	DisplayUnit   string                 `protobuf:"bytes,4,opt,name=display_unit,json=displayUnit,proto3" json:"display_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KpiValue) Reset() {
	*x = KpiValue{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KpiValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KpiValue) ProtoMessage() {}

func (x *KpiValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KpiValue.ProtoReflect.Descriptor instead.
func (*KpiValue) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *KpiValue) GetType() KpiType {
	if x != nil {
		return x.Type
	}
	return KpiType_KPI_TYPE_UNSPECIFIED
}

func (x *KpiValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *KpiValue) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *KpiValue) GetDisplayUnit() string {
	if x != nil {
		return x.DisplayUnit
	}
	return ""
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cell) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TableType              `protobuf:"varint,1,opt,name=type,proto3,enum=proto.smartpick.emh.v1.TableType" json:"type,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *Table) GetType() TableType {
	if x != nil {
		return x.Type
	}
	return TableType_TABLE_TYPE_UNSPECIFIED
}

func (x *Table) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Table) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *DataPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Timeseries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TimeseriesType         `protobuf:"varint,1,opt,name=type,proto3,enum=proto.smartpick.emh.v1.TimeseriesType" json:"type,omitempty"`
	SeriesName    string                 `protobuf:"bytes,2,opt,name=series_name,json=seriesName,proto3" json:"series_name,omitempty"`
	Points        []*DataPoint           `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	Aggregation   Aggregation            `protobuf:"varint,4,opt,name=aggregation,proto3,enum=proto.smartpick.emh.v1.Aggregation" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeseries) Reset() {
	*x = Timeseries{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeseries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeseries) ProtoMessage() {}

func (x *Timeseries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeseries.ProtoReflect.Descriptor instead.
func (*Timeseries) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *Timeseries) GetType() TimeseriesType {
	if x != nil {
		return x.Type
	}
	return TimeseriesType_TIMESERIES_TYPE_UNSPECIFIED
}

func (x *Timeseries) GetSeriesName() string {
	if x != nil {
		return x.SeriesName
	}
	return ""
}

func (x *Timeseries) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Timeseries) GetAggregation() Aggregation {
	if x != nil {
		return x.Aggregation
	}
	return Aggregation_AGGREGATION_UNSPECIFIED
}

// ----------------------------------------
// Requests / Responses
// ----------------------------------------
type GetMetricsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// what to include in the response
	IncludeKpis       bool             `protobuf:"varint,3,opt,name=include_kpis,json=includeKpis,proto3" json:"include_kpis,omitempty"`
	IncludeTables     []TableType      `protobuf:"varint,4,rep,packed,name=include_tables,json=includeTables,proto3,enum=proto.smartpick.emh.v1.TableType" json:"include_tables,omitempty"`
	IncludeTimeseries []TimeseriesType `protobuf:"varint,5,rep,packed,name=include_timeseries,json=includeTimeseries,proto3,enum=proto.smartpick.emh.v1.TimeseriesType" json:"include_timeseries,omitempty"`
	// bucket size for timeseries (e.g. 60s, 3600s). Ignored if
	// no timeseries are included.
	ResolutionSeconds int32               `protobuf:"varint,6,opt,name=resolution_seconds,json=resolutionSeconds,proto3" json:"resolution_seconds,omitempty"`
	ComparisonType    DeltaComparisonType `protobuf:"varint,7,opt,name=comparison_type,json=comparisonType,proto3,enum=proto.smartpick.emh.v1.DeltaComparisonType" json:"comparison_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *GetMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetMetricsRequest) GetIncludeKpis() bool {
	if x != nil {
		return x.IncludeKpis
	}
	return false
}

func (x *GetMetricsRequest) GetIncludeTables() []TableType {
	if x != nil {
		return x.IncludeTables
	}
	return nil
}

func (x *GetMetricsRequest) GetIncludeTimeseries() []TimeseriesType {
	if x != nil {
		return x.IncludeTimeseries
	}
	return nil
}

func (x *GetMetricsRequest) GetResolutionSeconds() int32 {
	if x != nil {
		return x.ResolutionSeconds
	}
	return 0
}

func (x *GetMetricsRequest) GetComparisonType() DeltaComparisonType {
	if x != nil {
		return x.ComparisonType
	}
	return DeltaComparisonType_DELTA_COMPARISON_TYPE_UNSPECIFIED
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kpis          []*KpiValue            `protobuf:"bytes,1,rep,name=kpis,proto3" json:"kpis,omitempty"`
	Tables        []*Table               `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
	Timeseries    []*Timeseries          `protobuf:"bytes,3,rep,name=timeseries,proto3" json:"timeseries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetricsResponse) GetKpis() []*KpiValue {
	if x != nil {
		return x.Kpis
	}
	return nil
}

func (x *GetMetricsResponse) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *GetMetricsResponse) GetTimeseries() []*Timeseries {
	if x != nil {
		return x.Timeseries
	}
	return nil
}

type ExportMetricsCsvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         TableType              `protobuf:"varint,1,opt,name=table,proto3,enum=proto.smartpick.emh.v1.TableType" json:"table,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportMetricsCsvRequest) Reset() {
	*x = ExportMetricsCsvRequest{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetricsCsvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetricsCsvRequest) ProtoMessage() {}

func (x *ExportMetricsCsvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetricsCsvRequest.ProtoReflect.Descriptor instead.
func (*ExportMetricsCsvRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *ExportMetricsCsvRequest) GetTable() TableType {
	if x != nil {
		return x.Table
	}
	return TableType_TABLE_TYPE_UNSPECIFIED
}

func (x *ExportMetricsCsvRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ExportMetricsCsvRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ExportMetricsCsvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportMetricsCsvResponse) Reset() {
	*x = ExportMetricsCsvResponse{}
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetricsCsvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetricsCsvResponse) ProtoMessage() {}

func (x *ExportMetricsCsvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetricsCsvResponse.ProtoReflect.Descriptor instead.
func (*ExportMetricsCsvResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *ExportMetricsCsvResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExportMetricsCsvResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_proto_smartpick_emh_v1_metrics_proto protoreflect.FileDescriptor

const file_proto_smartpick_emh_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"$proto/smartpick/emh/v1/metrics.proto\x12\x16proto.smartpick.emh.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x8e\x01\n" +
	"\bKpiValue\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.proto.smartpick.emh.v1.KpiTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12!\n" +
	"\fdisplay_unit\x18\x04 \x01(\tR\vdisplayUnit\"2\n" +
	"\x04Cell\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\"9\n" +
	"\x03Row\x122\n" +
	"\x05cells\x18\x01 \x03(\v2\x1c.proto.smartpick.emh.v1.CellR\x05cells\"\x89\x01\n" +
	"\x05Table\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.proto.smartpick.emh.v1.TableTypeR\x04type\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12/\n" +
	"\x04rows\x18\x03 \x03(\v2\x1b.proto.smartpick.emh.v1.RowR\x04rows\"[\n" +
	"\tDataPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xeb\x01\n" +
	"\n" +
	"Timeseries\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.proto.smartpick.emh.v1.TimeseriesTypeR\x04type\x12\x1f\n" +
	"\vseries_name\x18\x02 \x01(\tR\n" +
	"seriesName\x129\n" +
	"\x06points\x18\x03 \x03(\v2!.proto.smartpick.emh.v1.DataPointR\x06points\x12E\n" +
	"\vaggregation\x18\x04 \x01(\x0e2#.proto.smartpick.emh.v1.AggregationR\vaggregation\"\xce\x03\n" +
	"\x11GetMetricsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12!\n" +
	"\finclude_kpis\x18\x03 \x01(\bR\vincludeKpis\x12H\n" +
	"\x0einclude_tables\x18\x04 \x03(\x0e2!.proto.smartpick.emh.v1.TableTypeR\rincludeTables\x12U\n" +
	"\x12include_timeseries\x18\x05 \x03(\x0e2&.proto.smartpick.emh.v1.TimeseriesTypeR\x11includeTimeseries\x12-\n" +
	"\x12resolution_seconds\x18\x06 \x01(\x05R\x11resolutionSeconds\x12T\n" +
	"\x0fcomparison_type\x18\a \x01(\x0e2+.proto.smartpick.emh.v1.DeltaComparisonTypeR\x0ecomparisonType\"\xc5\x01\n" +
	"\x12GetMetricsResponse\x124\n" +
	"\x04kpis\x18\x01 \x03(\v2 .proto.smartpick.emh.v1.KpiValueR\x04kpis\x125\n" +
	"\x06tables\x18\x02 \x03(\v2\x1d.proto.smartpick.emh.v1.TableR\x06tables\x12B\n" +
	"\n" +
	"timeseries\x18\x03 \x03(\v2\".proto.smartpick.emh.v1.TimeseriesR\n" +
	"timeseries\"\xc4\x01\n" +
	"\x17ExportMetricsCsvRequest\x127\n" +
	"\x05table\x18\x01 \x01(\x0e2!.proto.smartpick.emh.v1.TableTypeR\x05table\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"P\n" +
	"\x18ExportMetricsCsvResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename*\x89\x01\n" +
	"\x13DeltaComparisonType\x12%\n" +
	"!DELTA_COMPARISON_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDELTA_COMPARISON_TYPE_PREVIOUS\x10\x01\x12'\n" +
	"#DELTA_COMPARISON_TYPE_SEVEN_DAY_AVG\x10\x02*\xe9\x02\n" +
	"\aKpiType\x12\x18\n" +
	"\x14KPI_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eKPI_TYPE_TOTAL_TASKS_COMPLETED\x10\x01\x12\x1f\n" +
	"\x1bKPI_TYPE_TOTAL_TASKS_MERGED\x10\x02\x12!\n" +
	"\x1dKPI_TYPE_TOTAL_TASKS_CANCELED\x10\x03\x12\x1c\n" +
	"\x18KPI_TYPE_COMPLETED_RATIO\x10\x04\x12\x18\n" +
	"\x14KPI_TYPE_NUM_DRIVERS\x10\x05\x12\x1a\n" +
	"\x16KPI_TYPE_NUM_FORKLIFTS\x10\x06\x12\x18\n" +
	"\x14KPI_TYPE_TOTAL_TASKS\x10\a\x12\x1d\n" +
	"\x19KPI_TYPE_TASK_UTILIZATION\x10\b\x12 \n" +
	"\x1cKPI_TYPE_REALISTIC_TASK_TIME\x10\t\x12\x16\n" +
	"\x12KPI_TYPE_APP_LOGIN\x10\n" +
	"\x12\x15\n" +
	"\x11KPI_TYPE_APP_TIME\x10\v*\x8d\x01\n" +
	"\tTableType\x12\x1a\n" +
	"\x16TABLE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTABLE_TYPE_TASKS_BY_DRIVER\x10\x01\x12\"\n" +
	"\x1eTABLE_TYPE_TASKS_BY_DEPARTMENT\x10\x02\x12 \n" +
	"\x1cTABLE_TYPE_TASKS_BY_FORKLIFT\x10\x03*\xd9\x01\n" +
	"\x0eTimeseriesType\x12\x1f\n" +
	"\x1bTIMESERIES_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTIMESERIES_TYPE_UTILIZATION\x10\x01\x12\x1f\n" +
	"\x1bTIMESERIES_TYPE_TASK_STATUS\x10\x02\x12'\n" +
	"#TIMESERIES_TYPE_REALISTIC_TASK_TIME\x10\x03\x12\x1d\n" +
	"\x19TIMESERIES_TYPE_APP_LOGIN\x10\x04\x12\x1c\n" +
	"\x18TIMESERIES_TYPE_APP_TIME\x10\x05*\x93\x01\n" +
	"\vAggregation\x12\x1b\n" +
	"\x17AGGREGATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fAGGREGATION_AVG\x10\x01\x12\x13\n" +
	"\x0fAGGREGATION_SUM\x10\x02\x12\x13\n" +
	"\x0fAGGREGATION_P50\x10\x03\x12\x13\n" +
	"\x0fAGGREGATION_P90\x10\x04\x12\x13\n" +
	"\x0fAGGREGATION_P99\x10\x052\x91\x02\n" +
	"\x0eMetricsService\x12s\n" +
	"\n" +
	"GetMetrics\x12).proto.smartpick.emh.v1.GetMetricsRequest\x1a*.proto.smartpick.emh.v1.GetMetricsResponse\"\x0e\x82\xd3\xe4\x93\x02\b:\x01*\"\x03/v1\x12\x89\x01\n" +
	"\x10ExportMetricsCsv\x12/.proto.smartpick.emh.v1.ExportMetricsCsvRequest\x1a0.proto.smartpick.emh.v1.ExportMetricsCsvResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/v1/csvB\x16Z\x14smartpick/emh/v1;emhb\x06proto3"

var (
	file_proto_smartpick_emh_v1_metrics_proto_rawDescOnce sync.Once
	file_proto_smartpick_emh_v1_metrics_proto_rawDescData []byte
)

func file_proto_smartpick_emh_v1_metrics_proto_rawDescGZIP() []byte {
	file_proto_smartpick_emh_v1_metrics_proto_rawDescOnce.Do(func() {
		file_proto_smartpick_emh_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smartpick_emh_v1_metrics_proto_rawDesc), len(file_proto_smartpick_emh_v1_metrics_proto_rawDesc)))
	})
	return file_proto_smartpick_emh_v1_metrics_proto_rawDescData
}

var file_proto_smartpick_emh_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_smartpick_emh_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_smartpick_emh_v1_metrics_proto_goTypes = []any{
	(DeltaComparisonType)(0),         // 0: proto.smartpick.emh.v1.DeltaComparisonType
	(KpiType)(0),                     // 1: proto.smartpick.emh.v1.KpiType
	(TableType)(0),                   // 2: proto.smartpick.emh.v1.TableType
	(TimeseriesType)(0),              // 3: proto.smartpick.emh.v1.TimeseriesType
	(Aggregation)(0),                 // 4: proto.smartpick.emh.v1.Aggregation
	(*KpiValue)(nil),                 // 5: proto.smartpick.emh.v1.KpiValue
	(*Cell)(nil),                     // 6: proto.smartpick.emh.v1.Cell
	(*Row)(nil),                      // 7: proto.smartpick.emh.v1.Row
	(*Table)(nil),                    // 8: proto.smartpick.emh.v1.Table
	(*DataPoint)(nil),                // 9: proto.smartpick.emh.v1.DataPoint
	(*Timeseries)(nil),               // 10: proto.smartpick.emh.v1.Timeseries
	(*GetMetricsRequest)(nil),        // 11: proto.smartpick.emh.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),       // 12: proto.smartpick.emh.v1.GetMetricsResponse
	(*ExportMetricsCsvRequest)(nil),  // 13: proto.smartpick.emh.v1.ExportMetricsCsvRequest
	(*ExportMetricsCsvResponse)(nil), // 14: proto.smartpick.emh.v1.ExportMetricsCsvResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_proto_smartpick_emh_v1_metrics_proto_depIdxs = []int32{
	1,  // 0: proto.smartpick.emh.v1.KpiValue.type:type_name -> proto.smartpick.emh.v1.KpiType
	6,  // 1: proto.smartpick.emh.v1.Row.cells:type_name -> proto.smartpick.emh.v1.Cell
	2,  // 2: proto.smartpick.emh.v1.Table.type:type_name -> proto.smartpick.emh.v1.TableType
	7,  // 3: proto.smartpick.emh.v1.Table.rows:type_name -> proto.smartpick.emh.v1.Row
	15, // 4: proto.smartpick.emh.v1.DataPoint.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 5: proto.smartpick.emh.v1.Timeseries.type:type_name -> proto.smartpick.emh.v1.TimeseriesType
	9,  // 6: proto.smartpick.emh.v1.Timeseries.points:type_name -> proto.smartpick.emh.v1.DataPoint
	4,  // 7: proto.smartpick.emh.v1.Timeseries.aggregation:type_name -> proto.smartpick.emh.v1.Aggregation
	15, // 8: proto.smartpick.emh.v1.GetMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	15, // 9: proto.smartpick.emh.v1.GetMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 10: proto.smartpick.emh.v1.GetMetricsRequest.include_tables:type_name -> proto.smartpick.emh.v1.TableType
	3,  // 11: proto.smartpick.emh.v1.GetMetricsRequest.include_timeseries:type_name -> proto.smartpick.emh.v1.TimeseriesType
	0,  // 12: proto.smartpick.emh.v1.GetMetricsRequest.comparison_type:type_name -> proto.smartpick.emh.v1.DeltaComparisonType
	5,  // 13: proto.smartpick.emh.v1.GetMetricsResponse.kpis:type_name -> proto.smartpick.emh.v1.KpiValue
	8,  // 14: proto.smartpick.emh.v1.GetMetricsResponse.tables:type_name -> proto.smartpick.emh.v1.Table
	10, // 15: proto.smartpick.emh.v1.GetMetricsResponse.timeseries:type_name -> proto.smartpick.emh.v1.Timeseries
	2,  // 16: proto.smartpick.emh.v1.ExportMetricsCsvRequest.table:type_name -> proto.smartpick.emh.v1.TableType
	15, // 17: proto.smartpick.emh.v1.ExportMetricsCsvRequest.start_time:type_name -> google.protobuf.Timestamp
	15, // 18: proto.smartpick.emh.v1.ExportMetricsCsvRequest.end_time:type_name -> google.protobuf.Timestamp
	11, // 19: proto.smartpick.emh.v1.MetricsService.GetMetrics:input_type -> proto.smartpick.emh.v1.GetMetricsRequest
	13, // 20: proto.smartpick.emh.v1.MetricsService.ExportMetricsCsv:input_type -> proto.smartpick.emh.v1.ExportMetricsCsvRequest
	12, // 21: proto.smartpick.emh.v1.MetricsService.GetMetrics:output_type -> proto.smartpick.emh.v1.GetMetricsResponse
	14, // 22: proto.smartpick.emh.v1.MetricsService.ExportMetricsCsv:output_type -> proto.smartpick.emh.v1.ExportMetricsCsvResponse
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_smartpick_emh_v1_metrics_proto_init() }
func file_proto_smartpick_emh_v1_metrics_proto_init() {
	if File_proto_smartpick_emh_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smartpick_emh_v1_metrics_proto_rawDesc), len(file_proto_smartpick_emh_v1_metrics_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smartpick_emh_v1_metrics_proto_goTypes,
		DependencyIndexes: file_proto_smartpick_emh_v1_metrics_proto_depIdxs,
		EnumInfos:         file_proto_smartpick_emh_v1_metrics_proto_enumTypes,
		MessageInfos:      file_proto_smartpick_emh_v1_metrics_proto_msgTypes,
	}.Build()
	File_proto_smartpick_emh_v1_metrics_proto = out.File
	file_proto_smartpick_emh_v1_metrics_proto_goTypes = nil
	file_proto_smartpick_emh_v1_metrics_proto_depIdxs = nil
}
