// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/smartpick/emh/v1/site_settings.proto

package emh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SiteSettingsService_GetSiteSettings_FullMethodName    = "/proto.smartpick.emh.v1.SiteSettingsService/GetSiteSettings"
	SiteSettingsService_UpdateSiteSettings_FullMethodName = "/proto.smartpick.emh.v1.SiteSettingsService/UpdateSiteSettings"
)

// SiteSettingsServiceClient is the client API for SiteSettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SiteSettingsService provides settings/configurations for EMH
type SiteSettingsServiceClient interface {
	// Get site settings (partial get with field mask)
	GetSiteSettings(ctx context.Context, in *GetSiteSettingsRequest, opts ...grpc.CallOption) (*GetSiteSettingsResponse, error)
	// Updates site settings (partial update with field mask)
	UpdateSiteSettings(ctx context.Context, in *UpdateSiteSettingsRequest, opts ...grpc.CallOption) (*UpdateSiteSettingsResponse, error)
}

type siteSettingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSiteSettingsServiceClient(cc grpc.ClientConnInterface) SiteSettingsServiceClient {
	return &siteSettingsServiceClient{cc}
}

func (c *siteSettingsServiceClient) GetSiteSettings(ctx context.Context, in *GetSiteSettingsRequest, opts ...grpc.CallOption) (*GetSiteSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSiteSettingsResponse)
	err := c.cc.Invoke(ctx, SiteSettingsService_GetSiteSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteSettingsServiceClient) UpdateSiteSettings(ctx context.Context, in *UpdateSiteSettingsRequest, opts ...grpc.CallOption) (*UpdateSiteSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSiteSettingsResponse)
	err := c.cc.Invoke(ctx, SiteSettingsService_UpdateSiteSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiteSettingsServiceServer is the server API for SiteSettingsService service.
// All implementations must embed UnimplementedSiteSettingsServiceServer
// for forward compatibility.
//
// SiteSettingsService provides settings/configurations for EMH
type SiteSettingsServiceServer interface {
	// Get site settings (partial get with field mask)
	GetSiteSettings(context.Context, *GetSiteSettingsRequest) (*GetSiteSettingsResponse, error)
	// Updates site settings (partial update with field mask)
	UpdateSiteSettings(context.Context, *UpdateSiteSettingsRequest) (*UpdateSiteSettingsResponse, error)
	mustEmbedUnimplementedSiteSettingsServiceServer()
}

// UnimplementedSiteSettingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSiteSettingsServiceServer struct{}

func (UnimplementedSiteSettingsServiceServer) GetSiteSettings(context.Context, *GetSiteSettingsRequest) (*GetSiteSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteSettings not implemented")
}
func (UnimplementedSiteSettingsServiceServer) UpdateSiteSettings(context.Context, *UpdateSiteSettingsRequest) (*UpdateSiteSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSiteSettings not implemented")
}
func (UnimplementedSiteSettingsServiceServer) mustEmbedUnimplementedSiteSettingsServiceServer() {}
func (UnimplementedSiteSettingsServiceServer) testEmbeddedByValue()                             {}

// UnsafeSiteSettingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SiteSettingsServiceServer will
// result in compilation errors.
type UnsafeSiteSettingsServiceServer interface {
	mustEmbedUnimplementedSiteSettingsServiceServer()
}

func RegisterSiteSettingsServiceServer(s grpc.ServiceRegistrar, srv SiteSettingsServiceServer) {
	// If the following call pancis, it indicates UnimplementedSiteSettingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SiteSettingsService_ServiceDesc, srv)
}

func _SiteSettingsService_GetSiteSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteSettingsServiceServer).GetSiteSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteSettingsService_GetSiteSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteSettingsServiceServer).GetSiteSettings(ctx, req.(*GetSiteSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SiteSettingsService_UpdateSiteSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSiteSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteSettingsServiceServer).UpdateSiteSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SiteSettingsService_UpdateSiteSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteSettingsServiceServer).UpdateSiteSettings(ctx, req.(*UpdateSiteSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SiteSettingsService_ServiceDesc is the grpc.ServiceDesc for SiteSettingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SiteSettingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.smartpick.emh.v1.SiteSettingsService",
	HandlerType: (*SiteSettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSiteSettings",
			Handler:    _SiteSettingsService_GetSiteSettings_Handler,
		},
		{
			MethodName: "UpdateSiteSettings",
			Handler:    _SiteSettingsService_UpdateSiteSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/smartpick/emh/v1/site_settings.proto",
}
