// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/smartpick/emh/v1/site_settings.proto

package emh

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSiteSettingsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SiteId string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// Fields to include in the response
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteSettingsRequest) Reset() {
	*x = GetSiteSettingsRequest{}
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteSettingsRequest) ProtoMessage() {}

func (x *GetSiteSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSiteSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_site_settings_proto_rawDescGZIP(), []int{0}
}

func (x *GetSiteSettingsRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *GetSiteSettingsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type GetSiteSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SiteSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteSettingsResponse) Reset() {
	*x = GetSiteSettingsResponse{}
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteSettingsResponse) ProtoMessage() {}

func (x *GetSiteSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSiteSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_site_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetSiteSettingsResponse) GetSettings() *SiteSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetSiteSettingsResponse) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type UpdateSiteSettingsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SiteId string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	// Fields to update
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Settings      *SiteSettings          `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteSettingsRequest) Reset() {
	*x = UpdateSiteSettingsRequest{}
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteSettingsRequest) ProtoMessage() {}

func (x *UpdateSiteSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSiteSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_site_settings_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSiteSettingsRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *UpdateSiteSettingsRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateSiteSettingsRequest) GetSettings() *SiteSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateSiteSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SiteSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteSettingsResponse) Reset() {
	*x = UpdateSiteSettingsResponse{}
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteSettingsResponse) ProtoMessage() {}

func (x *UpdateSiteSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSiteSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_site_settings_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSiteSettingsResponse) GetSettings() *SiteSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SiteSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Shifts        []*SiteShift           `protobuf:"bytes,4,rep,name=shifts,proto3" json:"shifts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteSettings) Reset() {
	*x = SiteSettings{}
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSettings) ProtoMessage() {}

func (x *SiteSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSettings.ProtoReflect.Descriptor instead.
func (*SiteSettings) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_site_settings_proto_rawDescGZIP(), []int{4}
}

func (x *SiteSettings) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *SiteSettings) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *SiteSettings) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *SiteSettings) GetShifts() []*SiteShift {
	if x != nil {
		return x.Shifts
	}
	return nil
}

type SiteShift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteShift) Reset() {
	*x = SiteShift{}
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteShift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteShift) ProtoMessage() {}

func (x *SiteShift) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartpick_emh_v1_site_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteShift.ProtoReflect.Descriptor instead.
func (*SiteShift) Descriptor() ([]byte, []int) {
	return file_proto_smartpick_emh_v1_site_settings_proto_rawDescGZIP(), []int{5}
}

func (x *SiteShift) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SiteShift) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SiteShift) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

var File_proto_smartpick_emh_v1_site_settings_proto protoreflect.FileDescriptor

const file_proto_smartpick_emh_v1_site_settings_proto_rawDesc = "" +
	"\n" +
	"*proto/smartpick/emh/v1/site_settings.proto\x12\x16proto.smartpick.emh.v1\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"\x16GetSiteSettingsRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\x94\x01\n" +
	"\x17GetSiteSettingsResponse\x12@\n" +
	"\bsettings\x18\x01 \x01(\v2$.proto.smartpick.emh.v1.SiteSettingsR\bsettings\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"\xb3\x01\n" +
	"\x19UpdateSiteSettingsRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12@\n" +
	"\bsettings\x18\x03 \x01(\v2$.proto.smartpick.emh.v1.SiteSettingsR\bsettings\"^\n" +
	"\x1aUpdateSiteSettingsResponse\x12@\n" +
	"\bsettings\x18\x01 \x01(\v2$.proto.smartpick.emh.v1.SiteSettingsR\bsettings\"\xbd\x01\n" +
	"\fSiteSettings\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x129\n" +
	"\x06shifts\x18\x04 \x03(\v2!.proto.smartpick.emh.v1.SiteShiftR\x06shifts\"\x91\x01\n" +
	"\tSiteShift\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime2\xcc\x02\n" +
	"\x13SiteSettingsService\x12\x8f\x01\n" +
	"\x0fGetSiteSettings\x12..proto.smartpick.emh.v1.GetSiteSettingsRequest\x1a/.proto.smartpick.emh.v1.GetSiteSettingsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/sites/{site_id}\x12\xa2\x01\n" +
	"\x12UpdateSiteSettings\x121.proto.smartpick.emh.v1.UpdateSiteSettingsRequest\x1a2.proto.smartpick.emh.v1.UpdateSiteSettingsResponse\"%\x82\xd3\xe4\x93\x02\x1f:\bsettings2\x13/v1/sites/{site_id}B\x16Z\x14smartpick/emh/v1;emhb\x06proto3"

var (
	file_proto_smartpick_emh_v1_site_settings_proto_rawDescOnce sync.Once
	file_proto_smartpick_emh_v1_site_settings_proto_rawDescData []byte
)

func file_proto_smartpick_emh_v1_site_settings_proto_rawDescGZIP() []byte {
	file_proto_smartpick_emh_v1_site_settings_proto_rawDescOnce.Do(func() {
		file_proto_smartpick_emh_v1_site_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smartpick_emh_v1_site_settings_proto_rawDesc), len(file_proto_smartpick_emh_v1_site_settings_proto_rawDesc)))
	})
	return file_proto_smartpick_emh_v1_site_settings_proto_rawDescData
}

var file_proto_smartpick_emh_v1_site_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_smartpick_emh_v1_site_settings_proto_goTypes = []any{
	(*GetSiteSettingsRequest)(nil),     // 0: proto.smartpick.emh.v1.GetSiteSettingsRequest
	(*GetSiteSettingsResponse)(nil),    // 1: proto.smartpick.emh.v1.GetSiteSettingsResponse
	(*UpdateSiteSettingsRequest)(nil),  // 2: proto.smartpick.emh.v1.UpdateSiteSettingsRequest
	(*UpdateSiteSettingsResponse)(nil), // 3: proto.smartpick.emh.v1.UpdateSiteSettingsResponse
	(*SiteSettings)(nil),               // 4: proto.smartpick.emh.v1.SiteSettings
	(*SiteShift)(nil),                  // 5: proto.smartpick.emh.v1.SiteShift
	(*fieldmaskpb.FieldMask)(nil),      // 6: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_proto_smartpick_emh_v1_site_settings_proto_depIdxs = []int32{
	6,  // 0: proto.smartpick.emh.v1.GetSiteSettingsRequest.read_mask:type_name -> google.protobuf.FieldMask
	4,  // 1: proto.smartpick.emh.v1.GetSiteSettingsResponse.settings:type_name -> proto.smartpick.emh.v1.SiteSettings
	6,  // 2: proto.smartpick.emh.v1.GetSiteSettingsResponse.read_mask:type_name -> google.protobuf.FieldMask
	6,  // 3: proto.smartpick.emh.v1.UpdateSiteSettingsRequest.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 4: proto.smartpick.emh.v1.UpdateSiteSettingsRequest.settings:type_name -> proto.smartpick.emh.v1.SiteSettings
	4,  // 5: proto.smartpick.emh.v1.UpdateSiteSettingsResponse.settings:type_name -> proto.smartpick.emh.v1.SiteSettings
	7,  // 6: proto.smartpick.emh.v1.SiteSettings.last_updated:type_name -> google.protobuf.Timestamp
	5,  // 7: proto.smartpick.emh.v1.SiteSettings.shifts:type_name -> proto.smartpick.emh.v1.SiteShift
	7,  // 8: proto.smartpick.emh.v1.SiteShift.start_time:type_name -> google.protobuf.Timestamp
	7,  // 9: proto.smartpick.emh.v1.SiteShift.end_time:type_name -> google.protobuf.Timestamp
	0,  // 10: proto.smartpick.emh.v1.SiteSettingsService.GetSiteSettings:input_type -> proto.smartpick.emh.v1.GetSiteSettingsRequest
	2,  // 11: proto.smartpick.emh.v1.SiteSettingsService.UpdateSiteSettings:input_type -> proto.smartpick.emh.v1.UpdateSiteSettingsRequest
	1,  // 12: proto.smartpick.emh.v1.SiteSettingsService.GetSiteSettings:output_type -> proto.smartpick.emh.v1.GetSiteSettingsResponse
	3,  // 13: proto.smartpick.emh.v1.SiteSettingsService.UpdateSiteSettings:output_type -> proto.smartpick.emh.v1.UpdateSiteSettingsResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_smartpick_emh_v1_site_settings_proto_init() }
func file_proto_smartpick_emh_v1_site_settings_proto_init() {
	if File_proto_smartpick_emh_v1_site_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smartpick_emh_v1_site_settings_proto_rawDesc), len(file_proto_smartpick_emh_v1_site_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smartpick_emh_v1_site_settings_proto_goTypes,
		DependencyIndexes: file_proto_smartpick_emh_v1_site_settings_proto_depIdxs,
		MessageInfos:      file_proto_smartpick_emh_v1_site_settings_proto_msgTypes,
	}.Build()
	File_proto_smartpick_emh_v1_site_settings_proto = out.File
	file_proto_smartpick_emh_v1_site_settings_proto_goTypes = nil
	file_proto_smartpick_emh_v1_site_settings_proto_depIdxs = nil
}
